### ISSUE TITLE
Bug related to mobile viewport

### ISSUE THREAD

**Issue by AcidOP** [Cwarcup/personal-blog#2]
**Describe the bug**
When viewing the website on mobile devices, the Mobile Navbar is accessible even when hamburger icon is not clicked. Can be viewed when swiping to the right.

**To Reproduce**
1. Go to [cwarcup.com](https://www.cwarcup.com/) on a mobile device
2. Swipe right
3. See error

**Expected behavior**
Mobile Navbar visible only when Hamburger button will be clicked

**Screenshots**
![Screenshot](https://cs-topia.vercel.app/cwarcup.JPG)

**System Info:**
 - OS: Android 12

**Browser Info:**
- Browser: Brave, Chrome
- Version: All latest

**Comment by Cwarcup** [comment]
Thank you for issuing such a detailed and thoughtful bug report!

I believed I've resolved the issue by adding the following:

```css
html,
body {
  overflow-x: hidden !important;
}

body {
  position: relative
}
```

Cheers
